# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,)

# https://neoforged.net/
neoforge_version=21.11.13-beta
neoforge_version_range=[21.11.12-beta,)

# Mod Properties
mod_version=1.2.1+1.21.11-neoforge
mod_group_id=de.dafuqs
mod_id=disableaccessibilityscreen
mod_name=Disable Accessibility Screen
mod_license=MIT
mod_authors=DaFuqs
mod_description=Removes the Accessibility Screen on first launch, introduced with 23w03a
issue_tracker_url=https://github.com/DaFuqs/DisableAccessibilityScreen/issues
display_url=https://github.com/DaFuqs/DisableAccessibilityScreen